window.BA_FIXTURES = {
  heroVideo: {
    mp4: "assets/hero-pubg.mp4",
    webm: "",
    poster: "assets/hero-poster.jpg"
  },
  stats: {
    playersOnline: 12480,
    matchesToday: 342,
    todaysJoins: 1842,
    totalMatches: 89420,
    ongoing: 28,
    totalWinnings: 2400000,
    arenaFilled: 847,
    arenaCapacity: 1200,
    apkVersion: "2.4.1",
    apkSizeMb: 86,
    apkDownloadUrl: "downloads/BattleAsia-v2.4.1.apk"
  },
  champion: {
    user: "ShadowNova",
    photo: "assets/players/player-shadownova.jpg",
    game: "PUBG Mobile",
    payout: "842K BAC",
    wins: 128,
    quoteKey: "championQuote"
  },
  matches: [
    { id: 1, name: "Dhaka Rush Cup", game: "PUBG Mobile", fee: 50, prize: 12000, filled: 72, cap: 100, status: "open" },
    { id: 2, name: "Asia Pro Scrims", game: "PUBG Mobile", fee: 100, prize: 45000, filled: 100, cap: 100, status: "full" },
    { id: 3, name: "Fire Zone Elite", game: "Free Fire", fee: 30, prize: 8000, filled: 45, cap: 48, status: "open" },
    { id: 4, name: "COD Blitz", game: "COD Mobile", fee: 40, prize: 15000, filled: 24, cap: 32, status: "open" },
    { id: 5, name: "Weekend Grand", game: "PUBG Mobile", fee: 200, prize: 120000, filled: 100, cap: 100, status: "complete" }
  ],
  games: [
    { id: "pubg", title: "PUBG Mobile", img: "assets/game-pubg.jpg", open: 42, popular: true, disabled: false },
    { id: "ff", title: "Free Fire", img: "assets/game-freefire.jpg", open: 18, popular: false, disabled: false },
    { id: "cod", title: "COD Mobile", img: "assets/game-cod.jpg", open: 11, popular: false, disabled: false },
    { id: "mlbb", title: "MLBB", img: "assets/game-mlbb.jpg", open: 7, popular: false, disabled: false },
    { id: "val", title: "Valorant Mobile", img: "", open: 0, popular: false, disabled: true, comingSoon: true }
  ],
  leaderboards: {
    profit: [
      { rank: 1, user: "ShadowNova", score: "842K BAC", photo: "assets/players/player-shadownova.jpg" },
      { rank: 2, user: "RavenX_BD", score: "710K BAC", photo: "assets/players/player-ravenx.jpg" },
      { rank: 3, user: "KiteStorm", score: "688K BAC", photo: "assets/players/player-kitestorm.jpg" },
      { rank: 4, user: "MiraAce", score: "521K BAC", photo: "assets/players/player-miraace.jpg" },
      { rank: 5, user: "ZeroLag", score: "498K BAC", photo: "assets/players/player-zerolag.jpg" },
      { rank: 6, user: "DhakaWolf", score: "467K BAC", photo: "assets/players/player-dhakawolf.jpg" },
      { rank: 7, user: "AsiaPulse", score: "441K BAC", photo: "assets/players/player-ravenx.jpg" },
      { rank: 8, user: "NeonSquad", score: "402K BAC", photo: "assets/players/player-zerolag.jpg" }
    ],
    killers: [
      { rank: 1, user: "HeadshotKing", score: "12,840", photo: "assets/players/player-headshotking.jpg" },
      { rank: 2, user: "FragLord", score: "11,220", photo: "assets/players/player-shadownova.jpg" },
      { rank: 3, user: "AceHunter", score: "10,905", photo: "assets/players/player-miraace.jpg" },
      { rank: 4, user: "BanglaSniper", score: "9,744", photo: "assets/players/player-dhakawolf.jpg" },
      { rank: 5, user: "StormRider", score: "9,102", photo: "assets/players/player-kitestorm.jpg" },
      { rank: 6, user: "PixelFury", score: "8,880", photo: "assets/players/player-fraglady.jpg" },
      { rank: 7, user: "ClutchGod", score: "8,410", photo: "assets/players/player-zerolag.jpg" },
      { rank: 8, user: "NightRaid", score: "8,055", photo: "assets/players/player-ravenx.jpg" }
    ]
  },
  faqTopics: ["payments", "fairplay", "rooms", "account"],
  faq: [
    { topic: "fairplay", qKey: "faq1q", aKey: "faq1a" },
    { topic: "fairplay", qKey: "faq2q", aKey: "faq2a" },
    { topic: "rooms", qKey: "faq3q", aKey: "faq3a" },
    { topic: "fairplay", qKey: "faq4q", aKey: "faq4a" },
    { topic: "payments", qKey: "faq5q", aKey: "faq5a" },
    { topic: "payments", qKey: "faq6q", aKey: "faq6a" },
    { topic: "payments", qKey: "faq7q", aKey: "faq7a" },
    { topic: "account", qKey: "faq8q", aKey: "faq8a" },
    { topic: "account", qKey: "faq9q", aKey: "faq9a" },
    { topic: "account", qKey: "faq10q", aKey: "faq10a" }
  ]
};

window.BA_I18N = {
  en: {
    navHome: "Home", navAbout: "About", navPlay: "Play", navRules: "Rules",
    signIn: "Sign in", signUp: "Sign up", join: "Join", signOut: "Sign out", enterArena: "Enter arena",
    heroEyebrow: "Mobile tournament arena · BAC coins · Bangladesh & Asia",
    heroLead: "Compete in fair PUBG-first rooms, climb leaderboards, and cash out real prizes with BAC.",
    siteName: "Battle Asia",
    heroTitle1: "Battle",
    heroTitle2: "Asia",
    downloadApk: "Download APK", live: "Live", playersOnline: "Players online", matchesToday: "Matches today",
    arenaSeats: "Arena seats", signUpCta: "Sign up free",
    pulseTitle: "Battle pulse", pulseLead: "Live stats from the arena — updated in real time.", todaysJoins: "Today's joins", totalMatches: "Total matches", ongoing: "Ongoing", totalWinnings: "Total winnings",
    matchLead: "Join open rooms or watch live brackets across top mobile titles.",
    topProfit: "Top profit", topKillers: "Top killers",
    matchHigh: "High prize", matchLive: "Live / ongoing", entryFee: "Entry", prizePool: "Prize pool", statusOpen: "Open", statusFull: "Full", statusComplete: "Complete",
    gamesTitle: "Pick your game", gamesLead: "PUBG-first, expanding across Asia’s biggest mobile esports titles.", openMatches: "{n} open matches", popular: "Popular", comingSoon: "Coming soon",
    aboutEyebrow: "About us", aboutTitle: "Built for mobile competitors", aboutP1: "BattleAsia is a premium mobile esports arena focused on fair rooms, transparent payouts, and community-driven tournaments across Bangladesh and wider Asia.",
    aboutP2: "Start with PUBG Mobile, expand across top titles, and grow your BAC balance through skill—not luck.",
    aboutCtaPlay: "Browse games", trust1: "Verified payouts", trust2: "Fair anti-cheat rooms", trust3: "Active community", trust4: "24/7 support", trust5: "Regional servers",
    modesTitle: "How to play", modesLead: "Choose a mode, enter a room, and climb the leaderboard.", mode1t: "Solo", mode1d: "Drop in alone and outlast the lobby.", mode2t: "Duo", mode2d: "Pair up for coordinated wins.", mode3t: "Squad", mode3d: "Four-player tactical room battles.", mode4t: "TDM", mode4d: "Fast respawn team deathmatch scrims.",
    rulesEyebrow: "Rules & FAQ", rulesTitle: "Play fair, win real", rulesLead: "Everything you need about rooms, prizes, and account safety.",
    rulesNote: "Staff may update rules; major changes are announced in-app.",
    topicPayments: "Payments", topicFair: "Fair play", topicRooms: "Rooms", topicAccount: "Account",
    supportCta: "Need help?", supportEmail: "Email support", supportChat: "Open chat",
    footerTag: "Mobile tournament arena for Bangladesh & Asia.",
    footerSupport: "Support", footerLegal: "Legal", footerQuick: "Quick links", terms: "Terms", privacy: "Privacy",
    trustRow: "Secure login · Fair play · Real payouts",
    email: "Email", password: "Password", remember: "Remember me", forgot: "Forgot password?", continue: "Continue", createAccount: "Create account", verify: "Verify",
    username: "In-game username", gameId: "PUBG / Game ID", phone: "Phone", server: "Game server", termsAgree: "I agree to Terms & Privacy",
    sendCode: "Send code", resendIn: "Resend in {n}s", otpTitle: "Verify your email", otpLead: "Enter the 6-digit code sent to",
    newPassword: "New password", confirmPassword: "Confirm password", resetTitle: "Reset password",
    google: "Google", discord: "Discord", createLink: "Create account", haveAccount: "Already have an account?",
    step1: "Account", step2: "Profile", checking: "Checking…", available: "Available", taken: "Taken",
    drawerApk: "Get the app", previewLoggedIn: "Preview logged in",
    championEyebrow: "Season champion", championTitle: "Victory pays real", championQuote: "Every final circle taught me patience. BattleAsia turned that into real BAC.",
    championGame: "Main game", championWins: "Verified wins", championPayout: "Season profit",
    termsTitle: "Terms of Service", privacyTitle: "Privacy Policy",
    toastArena: "Arena is outside this demo.", toastMatch: "Match lobby opens in full app.", toastSignedIn: "Welcome back, competitor!",
    faq1q: "What is fair play on BattleAsia?", faq1a: "We use room passwords, staff monitoring, and report review. Cheating leads to permanent bans and forfeited prizes.",
    faq2q: "Who operates tournaments?", faq2a: "Certified room hosts and BattleAsia staff run scheduled events with published rules before entry.",
    faq3q: "How do I get room ID & password?", faq3a: "After joining a match, room details appear in your match card 15 minutes before start.",
    faq4q: "How are prizes calculated?", faq4a: "Prize pools are fixed per event; placements follow the published bracket table minus platform fee.",
    faq5q: "Which payment methods are supported?", faq5a: "bKash, Nagad, and select crypto rails for deposits; withdrawals follow the same verified channels.",
    faq6q: "How do withdrawals work?", faq6a: "Request from wallet, complete KYC once, processing within 24–72 hours on business days.",
    faq7q: "Is there a referral program?", faq7a: "Share your link; earn BAC bonus when referrals complete their first paid match.",
    faq8q: "Can I change my username?", faq8a: "Once every 30 days from account settings after OTP confirmation.",
    faq9q: "How do I contact support?", faq9a: "Email support@battleasia.gg or use the floating chat for mock triage in this demo.",
    faq10q: "Age and eligibility?", faq10a: "You must be 18+ (or local age of majority) and comply with local gaming regulations."
  },
  bn: {
    navHome: "হোম", navAbout: "আমাদের সম্পর্কে", navPlay: "খেলুন", navRules: "নিয়ম",
    signIn: "সাইন ইন", signUp: "সাইন আপ", join: "যোগ দিন", signOut: "সাইন আউট", enterArena: "অ্যারেনায় ঢুকুন",
    heroEyebrow: "মোবাইল টুর্নামেন্ট · BAC কয়েন · বাংলাদেশ ও এশিয়া",
    heroLead: "ন্যাঞ্জস PUBG-প্রথম রুমে প্রতিযোগিতা করুন, লিডারবোর্ডে উঠুন, BAC দিয়ে আসল পুরস্কার নিন।",
    siteName: "ব্যাটল এশিয়া",
    heroTitle1: "ব্যাটল",
    heroTitle2: "এশিয়া",
    downloadApk: "APK ডাউনলোড", live: "লাইভ", playersOnline: "অনলাইন খেলোয়াড়", matchesToday: "আজকের ম্যাচ",
    arenaSeats: "অ্যারেনা আসন", signUpCta: "ফ্রি সাইন আপ",
    pulseTitle: "ব্যাটল পালস", pulseLead: "অ্যারেনার লাইভ পরিসংখ্যান — রিয়েল টাইমে আপডেট।", todaysJoins: "আজকের যোগ", totalMatches: "মোট ম্যাচ", ongoing: "চলমান", totalWinnings: "মোট জয়",
    matchLead: "খোলা রুমে যোগ দিন বা লাইভ ব্র্যাকেট দেখুন।",
    topProfit: "টপ প্রফিট", topKillers: "টপ কিলার",
    matchHigh: "বড় পুরস্কার", matchLive: "লাইভ / চলমান", entryFee: "এন্ট্রি", prizePool: "পুরস্কার", statusOpen: "খোলা", statusFull: "পূর্ণ", statusComplete: "সম্পন্ন",
    gamesTitle: "গেম বেছে নিন", gamesLead: "PUBG-প্রথম — এশিয়ার শীর্ষ মোবাইল esports টাইটেল।", openMatches: "{n}টি খোলা ম্যাচ", popular: "জনপ্রিয়", comingSoon: "শীঘ্রই",
    aboutEyebrow: "আমাদের সম্পর্কে", aboutTitle: "মোবাইল প্রতিযোগীদের জন্য", aboutP1: "BattleAsia ন্যায্য রুম, স্বচ্ছ payout এবং কমিউনিটি টুর্নামেন্টের প্রিমিয়াম মোবাইল esports অ্যারেনা।",
    aboutP2: "PUBG Mobile দিয়ে শুরু করুন, BAC বাড়ান দক্ষতা দিয়ে—ভাগ্য দিয়ে নয়।",
    aboutCtaPlay: "গেম দেখুন", trust1: "যাচাইকৃত payout", trust2: "ফেয়ার anti-cheat", trust3: "সক্রিয় কমিউনিটি", trust4: "২৪/৭ সাপোর্ট", trust5: "রিজионাল সার্ভার",
    modesTitle: "কিভাবে খেলবেন", modesLead: "মোড বেছে নিন, রুমে ঢুকুন, লিডারবোর্ডে উঠুন।", mode1t: "সোলো", mode1d: "একা নামুন, শেষ পর্যন্ত টিকে থাকুন।", mode2t: "ডুও", mode2d: "দুজন মিলে জয়।", mode3t: "স্কোয়াড", mode3d: "চারজনের ট্যাকটিক্যাল ব্যাটল।", mode4t: "TDM", mode4d: "দ্রুত টিম ডেথম্যাচ।",
    rulesEyebrow: "নিয়ম ও FAQ", rulesTitle: "ন্যাঞ্জস খেলুন, আসল জিতুন", rulesLead: "রুম, পুরস্কার ও অ্যাকাউন্ট নিরাপত্তা সম্পর্কে সব।",
    rulesNote: "স্টাফ নিয়ম আপডেট করতে পারে; বড় পরিবর্তন অ্যাপে জানানো হয়।",
    topicPayments: "পেমেন্ট", topicFair: "ফেয়ার প্লে", topicRooms: "রুম", topicAccount: "অ্যাকাউন্ট",
    supportCta: "সাহায্য দরকার?", supportEmail: "ইমেইল সাপোর্ট", supportChat: "চ্যাট খুলুন",
    footerTag: "বাংলাদেশ ও এশিয়ার মোবাইল টুর্নামেন্ট অ্যারেনা।",
    footerSupport: "সাপোর্ট", footerLegal: "আইনি", footerQuick: "দ্রুত লিংক", terms: "শর্তাবলী", privacy: "গোপনীয়তা",
    trustRow: "নিরাপদ লগইন · ফেয়ার প্লে · আসল payout",
    email: "ইমেইল", password: "পাসওয়ার্ড", remember: "মনে রাখুন", forgot: "পাসওয়ার্ড ভুলে গেছেন?", continue: "এগিয়ে যান", createAccount: "অ্যাকাউন্ট তৈরি", verify: "যাচাই",
    username: "ইন-গেম ইউজারনেম", gameId: "PUBG / Game ID", phone: "ফোন", server: "গেম সার্ভার", termsAgree: "শর্ত ও গোপনীয়তায় সম্মত",
    sendCode: "কোড পাঠান", resendIn: "{n} সেকেন্ডে পুনরায়", otpTitle: "ইমেইল যাচাই", otpLead: "৬-অঙ্কের কোড দিন",
    newPassword: "নতুন পাসওয়ার্ড", confirmPassword: "নিশ্চিত করুন", resetTitle: "পাসওয়ার্ড রিসেট",
    google: "Google", discord: "Discord", createLink: "অ্যাকাউন্ট তৈরি", haveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে?",
    step1: "অ্যাকাউন্ট", step2: "প্রোফাইল", checking: "যাচাই…", available: "উপলব্ধ", taken: "নেওয়া",
    drawerApk: "অ্যাপ নিন", previewLoggedIn: "লগইন প্রিভিউ",
    championEyebrow: "সিজন চ্যাম্পিয়ন", championTitle: "জয় মানে আসল", championQuote: "প্রতিটি ফাইনাল সার্কল ধৈর্য শেখায়। BattleAsia সেটাকে আসল BAC-এ বদলায়।",
    championGame: "মূল গেম", championWins: "যাচাইকৃত জয়", championPayout: "সিজন প্রফিট",
    termsTitle: "সেবার শর্ত", privacyTitle: "গোপনীয়তা নীতি",
    toastArena: "অ্যারেনা এই ডেমোর বাইরে।", toastMatch: "ম্যাচ লবি ফুল অ্যাপে খুলবে।", toastSignedIn: "স্বাগতম, প্রতিযোগী!",
    faq1q: "BattleAsia-তে fair play কী?", faq1a: "রুম পাসওয়ার্ড, স্টাফ মনিটরিং ও রিপোর্ট রিভিউ। চিটিং = ব্যান ও পুরস্কার বাতিল।",
    faq2q: "টুর্নামেন্ট কে চালায়?", faq2a: "সার্টিফাইড হোস্ট ও BattleAsia স্টাফ নির্ধারিত ইভেন্ট চালায়।",
    faq3q: "Room ID ও পাসওয়ার্ড কোথায়?", faq3a: "ম্যাচে যোগ দিলে শুরুর ১৫ মিনিট আগে কার্ডে দেখাবে।",
    faq4q: "পুরস্কার কীভাবে?", faq4a: "ইভেন্ট অনুযায়ী ফিক্সড পুল; প্লেসমেন্ট টেবিল অনুযায়ী।",
    faq5q: "কোন পেমেন্ট?", faq5a: "bKash, Nagad ও নির্বাচিত crypto।",
    faq6q: "উত্তোলন?", faq6a: "ওয়ালেট থেকে অনুরোধ, KYC, ২৪–৭২ ঘণ্টা।",
    faq7q: "রেফারেল?", faq7a: "লিংক শেয়ার; প্রথম paid ম্যাচে বোনাস BAC।",
    faq8q: "ইউজারনেম পরিবর্তন?", faq8a: "৩০ দিনে একবার OTP সহ।",
    faq9q: "সাপোর্ট?", faq9a: "support@battleasia.gg বা ফ্লোটিং চ্যাট।",
    faq10q: "বয়স ও যোগ্যতা?", faq10a: "১৮+ (বা স্থানীয় বয়স) ও স্থানীয় আইন মেনে।"
  }
};
