export const ALL_PERMISSIONS = [
  { key: 'users.view', label: 'View Users', category: 'users' },
  { key: 'users.create', label: 'Create Users', category: 'users' },
  { key: 'users.edit', label: 'Edit Users', category: 'users' },
  { key: 'users.delete', label: 'Delete Users', category: 'users' },
  { key: 'matches.view', label: 'View Matches', category: 'matches' },
  { key: 'matches.create', label: 'Create Matches', category: 'matches' },
  { key: 'matches.edit', label: 'Edit Matches', category: 'matches' },
  { key: 'matches.delete', label: 'Delete Matches', category: 'matches' },
  { key: 'matches.result', label: 'Manage Match Results', category: 'matches' },
  { key: 'payments.view', label: 'View Payments', category: 'payments' },
  { key: 'payments.manage', label: 'Manage Payments', category: 'payments' },
  { key: 'notifications.send', label: 'Send Notifications', category: 'notifications' },
  { key: 'feed.view', label: 'View Feed', category: 'feed' },
  { key: 'feed.create', label: 'Create Feed', category: 'feed' },
  { key: 'feed.edit', label: 'Edit Feed', category: 'feed' },
  { key: 'feed.delete', label: 'Delete Feed', category: 'feed' },
  { key: 'customer-support.view', label: 'View Support', category: 'customer-support' },
  { key: 'customer-support.reply', label: 'Reply Support', category: 'customer-support' },
  { key: 'customer-support.close', label: 'Close Support', category: 'customer-support' },
  { key: 'shop.view', label: 'View Shop', category: 'shop' },
  { key: 'shop.create', label: 'Create Shop Items', category: 'shop' },
  { key: 'shop.edit', label: 'Edit Shop Items', category: 'shop' },
  { key: 'shop.delete', label: 'Delete Shop Items', category: 'shop' },
] as const;
